### ISSUE TITLE
Getting Host not allowed

### ISSUE THREAD

**Issue by houshuang** [heta-io/tap#128]
I used a previous version of this, which worked, but with the current head (c36826edca), I receive Host not allowed localhost:9000, whether I try localhost or 127.0.0.1, and whether / or /graphiql.

**Comment by andrewresearch** [comment]
Sorry @houshuang, we need to put something in the docs about this. You need to set the environment variable `TAP_HOSTS` to whatever host you are running on (including the port).

**Comment by weiwei5444** [comment]
Hi, I had the same problem as I followed the `Quick Start` instruction. I've added the `export  TAP_HOSTS=http://localhost:9000` to the `~/.bash_profile` in my Mac, but I still receive `p.f.h.AllowedHostsFilter - Host not allowed: localhost:9000` and a 'Bad Request' page is responded.

Also the errors received:

> [error] a.a.OneForOneStrategy - Unable to provision, see the following errors:
> 
> 1) Error injecting constructor, java.lang.ExceptionInInitializerError
>   at tap.analysis.wordvector.WordVectorActor.<init>(WordVectorActor.scala:34)
>   while locating tap.analysis.wordvector.WordVectorActor
> 
> 1 error
> akka.actor.ActorInitializationException: akka://application/user/wordvector: exception during creation
> .....

Thanks.

**Comment by andrewresearch** [comment]
Try export TAP_HOSTS=localhost:9000 without the http://

**Comment by weiwei5444** [comment]
It worked. Thanks, Professor Gibson.
