### ISSUE TITLE
For each TAP query, the description field needs to be updated with more detail

### ISSUE THREAD

**Issue by andrewresearch** [heta-io/tap#179]
The description field should provide:

1. A detailed description of what the query does
2. A URL for the relevant documentation page (a stub should be created if it doesn't exist)
3. A URL to the specific exemplar query

This should be stored in a separate Object that is inserted programmatically. That way this information can be stored once in TAP and used in multiple places (e.g. also in authority field info.)

**Comment by ViolentCrumble** [comment]
Complete
