### ISSUE TITLE
Quick Start needs to be updated

### ISSUE THREAD

**Issue by andrewresearch** [heta-io/tap#202]
The current quick start is building from source, and still references ```uts-cic``` as the repo. This needs to be updated to the new ```heta-io``` repo. Also, a quick start with docker should probably go first as that is the fastest way for someone to get TAP up and running.

**Comment by ViolentCrumble** [comment]
started work on this, See pull request

**Comment by ViolentCrumble** [comment]
Now Complete. See pull request
