### ISSUE TITLE
Add dl4j to enable ML capabilities

### ISSUE THREAD

**Issue by andrewresearch** [heta-io/tap#29]
In particular, we need a common way of creating word and sentence vectors, so ideally we'll create an existing model or models, and then TAP can process new text using existing models.

**Comment by quanie** [comment]
Hi Andrew, while reading this description, I'm thinking of a model learned from a training text corpus to find a group of similar words for the input. What do you mean by creating word? What are the training data?

**Comment by andrewresearch** [comment]
word vectors and sentence vectors using a library like dl4j.

**Comment by quanie** [comment]
Do you want to implement this as an Actor? or just a class that return word vectors and sentence vectors?

**Comment by quanie** [comment]
Also, is it required to train word vectors and sentence vectors with some training data, or to load a pre-trained models? For example, there is a public pre-trained word vectors with Google News. However, I haven't found any pre-trained sentence vectors.

**Comment by andrewresearch** [comment]
I'd be happy start with word vectors from a pre-trained model.

**Comment by quanie** [comment]
I raised a pull request for this issue and found a problem. The pre-trained word model from Google News is quite big (1.5GB). Github does not allow to push it. Where should I put the file and can load it in the project? It is in models folder currently.

**Comment by andrewresearch** [comment]
Yes, you can't store the model on GitHub. The best thing to do is to remove the file from your current commit and update the pull request so that it goes through without the file. Then, update the docs with a link to where the model can be downloaded from, and each user of TAP will need to download this before they build it. For now, we should also make sure that TAP compiles and runs *without* this file. ie. the feature should be optional, and should fail gracefully if the model is not present.
